require("ext.options")
require("ext.plugins.lualine")
require("ext.plugins.which-key")
require("ext.plugins.gitsigns")
require("ext.plugins.mini")
require("ext.keymaps")
require("ext.plugins.telescope")
pcall(require, "ext.plugins.dadbod")
require("ext.plugins.treesitter")
require("ext.plugins.neo-tree")
require("ext.plugins.coc")
require("ext.plugins.ale")
