require("ext.options")
local utils = require("ext.utils")
require("ext.commands")
require("ext.plugins.bufferline")
require("ext.plugins.lualine")
require("ext.plugins.which-key")
require("ext.plugins.gitsigns")
require("ext.plugins.mini")
require("ext.keymaps")
require("ext.plugins.telescope")
require("ext.plugins.persisted")
pcall(require, "ext.plugins.dadbod")
require("ext.plugins.treesitter")
require("ext.plugins.neo-tree")
require("ext.plugins.coc")
require("ext.plugins.ale")

-- setup autocommands from utils
utils.setup_autocommands()
