projects = { "/home/adam/projects" = { trust_level = "trusted" } }
model_reasoning_effort = "high"
model = "gpt-5.1-codex-max"

[tools]
websearch = true

features.web_search_request = true

tools.view_image = true

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true
experimental_use_profile = true
