require("aw.options")
require("aw.plugins.lualine")
require("aw.plugins.bufferline")
require("aw.plugins.which-key")
require("aw.plugins.gitsigns")
require("aw.plugins.mini")
require("aw.keymaps")
require("aw.plugins.telescope")
pcall(require, "aw.plugins.dadbod")
require("aw.plugins.treesitter")
require("aw.plugins.neo-tree")
require("aw.plugins.cmp")
require("aw.plugins.lsp")
