name: Build Nix environments

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
  push:
    paths:
      - '**'
      - '!**.md'
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:
  darwin:
    name: Build darwin environment
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v8
        with:
          name: hardselius
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
            
      - name: If scheduled, update sources
        if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          nix flake update --recreate-lock-file

      - name: Build and switch to nix-darwin env
        run: |
          # Create /run directory
          echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
          /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B 2>/dev/null || true
          # Prevent conflict between Cachix installed by workflow and the one installed in the config
          nix-env --set-flag priority 1 cachix
          # Build and switch to bootstrap config
          nix build .#darwinConfigurations.bootstrap.system
          ./result/sw/bin/darwin-rebuild switch --flake .#bootstrap
          # Build and switch to full config
          sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.backup-before-darwin
          sudo mv /etc/zshenv /etc/zshenv.backup-before-darwin
          /run/current-system/sw/bin/darwin-rebuild switch --flake .#ghActions

      - name: If scheduled, push commit with updated sources
        if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          git add --all
          git commit -m "Update sources"
          git push
